title: sturdy-fiesta
description: ""
owner_name: Soham360
github_username: Soham Kamat
github_repo: "sturdy-fiesta"
baseurl: "/sturdy-fiesta"
remote_theme: jekyll/minima
minima:
plugins:
- jekyll-remote-theme
future: true
