title: sturdy-fiesta
description: ""
owner_name: Soham360
github_username: Soham Kamat
github_repo: "sturdy-fiesta"
baseurl: "/sturdy-fiesta"
remote_theme: jekyll/minima
minima:
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
