title: sturdy-fiesta
description: "Equipe de no papels 🚫📄"
owner_name: Soham360
github_username: Soham Kamat
github_repo: "sturdy-fiesta"
baseurl: "/sturdy-fiesta"
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/Soham360"}
    - { platform: github, user_url: "https://github.com/AniCricKet"}
    - { platform: github, user_url: "https://github.com/DasMoge124"}
    - { platform: github, user_url: "https://github.com/Orlando-c"}
    - { platform: github, user_url: "https://github.com/Soham360/sturdy-fiesta"}
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
